### ISSUE TITLE
Circle Ci doesn't seem to be running

### ISSUE THREAD

**Issue by James-Crean** [CDAT/vcdat#246]
Code merges don't trigger Circle Ci, which means there are no mac builds for vcdat in the new cdat anaconda repo.

**Comment by doutriaux1** [comment]
actually even though they do not show up, they are triggered... But fail:
```
  Test:	source activate  /Users/distiller/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol 
  Build:	source activate  /Users/distiller/conda-bld/_build_env 


Traceback (most recent call last):
  File "/Users/distiller/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/distiller/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/Users/distiller/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/Users/distiller/miniconda/lib/python2.7/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/distiller/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 2097, in build_tree
    notest=notest,
  File "/Users/distiller/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 1287, in build
    raise e
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: set(['vcs-js', 'vcs'])
Uploading
Using Anaconda API: https://api.anaconda.org
```

Investigating

**Comment by doutriaux1** [comment]
see: https://github.com/CDAT/vcdat/pull/247
